###
## Libraries and samples for analysis SA1035 10x
######################################################
library:
  SCRNA10X_SA_CHIP0146_004:
    passage: X7
    mouse_id: SA535X7XB03305
    library_id: SCRNA10X_SA_CHIP0146_004
    treatmentSt: UTU
    batch_info: CHIP0146
    PDX: SA535
  SCRNA10X_SA_CHIP0146_006:
    passage: X6
    mouse_id: SA535X6XB03099
    library_id: SCRNA10X_SA_CHIP0146_006
    treatmentSt: UU
    batch_info: CHIP0146
    PDX: SA535
  SCRNA10X_SA_CHIP0148_001:
    passage: X4
    mouse_id: SA535X4XB02498
    library_id: SCRNA10X_SA_CHIP0148_001
    treatmentSt: U
    batch_info: CHIP0148
    PDX: SA535
  SCRNA10X_SA_CHIP0173_001:
    passage: X9
    mouse_id: SA535X9XB03616
    library_id: SCRNA10X_SA_CHIP0173_001
    treatmentSt: UTTTU
    batch_info: CHIP0173
    PDX: SA535
  SCRNA10X_SA_CHIP0173_002:
    passage: X9
    mouse_id: SA535X9XB03617
    library_id: SCRNA10X_SA_CHIP0173_002
    treatmentSt: UTTTT
    batch_info: CHIP0173
    PDX: SA535
  SCRNA10X_SA_CHIP0175_001:
    passage: X6
    mouse_id: SA535X6XB03101
    library_id: SCRNA10X_SA_CHIP0175_001
    treatmentSt: UT
    batch_info: CHIP0175
    PDX: SA535
  SCRNA10X_SA_CHIP0182_001:
    passage: X7
    mouse_id: SA535X7XB03304
    library_id: SCRNA10X_SA_CHIP0182_001
    treatmentSt: UTT
    batch_info: CHIP0182
    PDX: SA535
  SCRNA10X_SA_CHIP0182_002:
    passage: X8
    mouse_id: SA535X8XB03431
    library_id: SCRNA10X_SA_CHIP0182_002
    treatmentSt: UTTT
    batch_info: CHIP0182
    PDX: SA535
  SCRNA10X_SA_CHIP0184_001:
    passage: X7
    mouse_id: SA535X7XB03305
    library_id: SCRNA10X_SA_CHIP0184_001
    treatmentSt: UTU
    batch_info: CHIP0184
    PDX: SA535
  SCRNA10X_SA_CHIP0184_002:
    passage: X8
    mouse_id: SA535X8XB03434
    library_id: SCRNA10X_SA_CHIP0184_002
    treatmentSt: UTTU
    batch_info: CHIP0184
    PDX: SA535
  SCRNA10X_SA_CHIP0189_001:
    passage: X7
    mouse_id: SA535X7XB03448
    library_id: SCRNA10X_SA_CHIP0189_001
    treatmentSt: UUU
    batch_info: CHIP0189
    PDX: SA535
  SCRNA10X_SA_CHIP0189_002:
    passage: X8
    mouse_id: SA535X8XB03663
    library_id: SCRNA10X_SA_CHIP0189_002
    treatmentSt: UUUU
    batch_info: CHIP0189
    PDX: SA535
  SCRNA10X_SA_CHIP0195_001:
    passage: X9
    mouse_id: SA535X8XB03664
    library_id: SCRNA10X_SA_CHIP0195_001
    treatmentSt: UUUU
    batch_info: CHIP0195
    PDX: SA535
  TENX048:
    passage: X5
    mouse_id: SA535X5XB02895
    library_id: TENX048
    treatmentSt: U
    batch_info: CHIP0048SA
    PDX: SA535



# Snakemake parameters
############################



# Snakemake activated rules
############################
download_data: True
merge_data: True
cell_cycle_detection: True
verification_qc: False
filter_data: True
merge_filter_data: True
normalize_data: True
clustering_data: True
deg_analysis: False
batch_effect_estimation: False
normalized_samples: True

# Snakemake filtering data params
############################
max_mito: 20
max_ribo: 60
min_pc_detected: 100
min_features: 1000
min_pc_sum: 500

# Snakemake clustering params
############################
resolution: 0.1

# Snakemake DEG params
############################
p_adjust: 0.0125
min_logfc: 0.25
#cluster_rm: '2'

# Directory parameters: Please update all fields
# nextflow_dir: for corrupt-grow pipeline only
############################################
project_10x_dir: '/home/htran/Projects/farhia_project/rscript/'
download_10x_dir: '/home/htran/storage/datasets/drug_resistance_RNAseq/SA535_CYS_human'
results_10x_dir: '/home/htran/storage/datasets/drug_resistance/dlp_results/SA535_rna_cys'
