---
title: "Explore SA609"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressPackageStartupMessages({
  library(tidyverse)
  library(scater)
})
```


```{r}
sce <- readRDS("../../results/v1/outputs/integrate/batch_correct/SA906b.rds")
```

```{r}
table(sce$id)
```

```{r}
plotReducedDim(sce, "scanorama_TSNE", colour_by = "total_counts")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "total_features_by_counts")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "id")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "pct_counts_mitochondrial")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "MALAT1")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "VIM")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "JUN")
```


Using clonealign fit


```{r}
ca_x3 <- readRDS("../../results/v1/outputs/align_clones/clonealign_fit/SA609X3XB01584.rds")
ca_x10 <- readRDS("../../results/v1/outputs/align_clones/clonealign_fit/SA609X10XB02454.rds")
```


```{r}
ca_x3 <- clonealign:::recompute_clone_assignment(ca_x3, 0.51)
ca_x10 <- clonealign:::recompute_clone_assignment(ca_x10, 0.51)
```

```{r}
clone_fit <- bind_rows(
  ca_x3$clone_fit,
  ca_x10$clone_fit
)

colnames(sce) <- sce$Barcode
sce <- sce[, clone_fit$Barcode]
sce$clone <- clone_fit$clone
```


```{r}
plotReducedDim(sce, "scanorama_TSNE", colour_by = "id")
plotReducedDim(sce, "scanorama_TSNE", colour_by = "clone")
```

```{r}
sce <- runPCA(sce)
plotPCA(sce, colour_by = "id")
plotPCA(sce, colour_by = "clone")
```


# Clonealign with all clones?

```{r}
load("/cellassign/fitness-scrna/results/dumps/")
```




## Can we look at smoothed expression?


```{r}
sce <- getBMFeatureAnnos(sce, 
                         ids = rowData(sce)$ID,
                         attributes = c("ensembl_gene_id", "chromosome_name", "start_position", "end_position"),
                         dataset = "hsapiens_gene_ensembl")
```


##



```{r}
sce$crap_clust <- 1 * ( reducedDim(sce, 'scanorama_TSNE')[,2] > 5 )
markers <- scran::findMarkers(sce, sce$crap_clust)
```


```{r}
hist(sce$pct_counts_mitochondrial, breaks = 100)
```



```{r}
rownames(sce) <- scater::uniquifyFeatureNames(rowData(sce)$ID, rowData(sce)$Symbol)
```

```{r}
plotReducedDim(sce, "scanorama_TSNE", colour_by = "EPCAM")
```

# X10

```{r}
load("../../results/dumps/clonealign-dump-SA609X10XB02454.Rdata")

sce_tmp <- sce_filtered[, sample(ncol(sce_filtered), 200)]
```

```{r}
load("../../data/external/recount2/rse_gene_breast.Rdata")
gtex_counts <- assay(rse_gene, 'counts')
mean_counts <- rowMeans(gtex_counts)
unique_ids <- gsub("\\.[-0-9]+", "", rownames(gtex_counts))
names(mean_counts) <- unique_ids
mean_counts <- mean_counts[rownames(sce_tmp)]
```


```{r}
devtools::load_all("/cellassign/clonealign/")
ca <- run_clonealign(sce_tmp, 
                     cnv_mat_remapped,
                     initial_shrinks = c(1,2,5), #args$initial_shrink,
                     n_repeats = 1,
                     mc_samples = 1,
                     learning_rate = 0.07,
                     max_iter = 1e3,
                     data_init_mu = mean_counts,
                     clone_call_probability = 0.9)

```

```{r}
library(biomaRt)

ensembl <- useMart("ensembl")
ensembl <- useDataset("hsapiens_gene_ensembl", mart=ensembl)
bm <- getBM(attributes = c("ensembl_gene_id", "chromosome_name", "start_position"),
      filters = c("ensembl_gene_id"),
      values = rowData(sce_filtered)$ID,
      mart = ensembl) %>% 
  as_data_frame()

# txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
```


```{r}
cor_df <- tibble(ensembl_gene_id = ca$retained_genes,
                 corr = ca$correlations)

print(dplyr::count(bm, chromosome_name))

inner_join(cor_df, bm) %>% 
  ggplot(aes(x = factor(chromosome_name), y = corr)) +
  geom_violin()
```

```{r}
df <- cnv_mat_remapped %>% 
  as.data.frame() %>% 
  rownames_to_column('ensembl_gene_id') %>% 
  inner_join(bm) %>% 
  inner_join(cor_df) %>% 
  dplyr::mutate(pos_cor = corr > 0) %>% 
  gather(clone, copy_number, -ensembl_gene_id, -chromosome_name, -start_position, -corr, -pos_cor)

dplyr::filter(df, pos_cor) %>% 
  ggplot(aes(x = ensembl_gene_id, y = copy_number, colour = clone)) +
  geom_point() +
  facet_wrap(~ chromosome_name, scales = "free")

dplyr::filter(df, !pos_cor) %>% 
  ggplot(aes(x = ensembl_gene_id, y = copy_number, colour = clone)) +
  geom_point() +
  facet_wrap(~ chromosome_name, scales = "free")

```


# X3

```{r}
load("../../results/dumps/clonealign-dump-SA609X3XB01584.Rdata")
```

```{r}
sce_tmp <- sce_subset[, sample(ncol(sce_filtered), 1000)]
sce_tmp <- sce_tmp[rownames(cnv_mat_remapped),]
plotReducedDim(sce_tmp, "scanorama_TSNE", colour_by = "pct_counts_mitochondrial")
```

```{r}
# sce_tmp <- sce_tmp[, reducedDim(sce_tmp, 'scanorama_TSNE')[,2] > 5]
```


```{r}
devtools::load_all("/cellassign/clonealign/")

ca <- run_clonealign(sce_tmp, 
                     cnv_mat_remapped,
                     initial_shrinks = c(0, 10), #args$initial_shrink,
                     n_repeats = 3,
                     mc_samples = 1,
                     learning_rate = 0.05,
                     max_iter = 2e2,
                     data_init_mu = TRUE,
                     clone_call_probability = 0.9)

```


```{r}
sce_tmp$clone <- ca$clone
plotReducedDim(sce_tmp, "scanorama_TSNE", colour_by = "clone")
sce_tmp <- runPCA(sce_tmp)
sce_tmp <- runUMAP(sce_tmp)
plotUMAP(sce_tmp, colour_by = "clone")
```


```{r}
load("../../data/external/recount2/rse_gene_breast.Rdata")

sce_breast <- SingleCellExperiment(assays = list(counts = assay(rse_gene, 'counts')),
                                   colData = colData(rse_gene),
                                   rowData = rowData(rse_gene))

sce_breast <- normalize(sce_breast)
```

```{r}
rowData(sce_breast)$mean_exprs <- rowMeans(as.matrix(logcounts(sce_breast)))
rowData(sce_filtered)$mean_exprs <- rowMeans(as.matrix(logcounts(sce_filtered)))
```

```{r}
rowData(sce_breast)$symbol <- sapply(rowData(sce_breast)$symbol, `[[`, 1)

df_exprs <- left_join(
  dplyr::select(as.data.frame(rowData(sce_filtered)), Symbol, mean_exprs),
  dplyr::select(as.data.frame(rowData(sce_breast)), Symbol = symbol, mean_exprs),
  by = "Symbol",
  suffix = c("_SA532", "_GTEX")
)

mm <- match(rowData(sce_filtered)$Symbol, df_exprs$Symbol)

df_exprs <- df_exprs[mm,]
```

```{r}
ggplot(df_exprs, aes(x = mean_exprs_GTEX, y = mean_exprs_SA532)) +
  geom_point()
```


```{r}

```




```{r}
devtools::load_all("/cellassign/clonealign")

rowData(sce_filtered)$mean_exprs_GTEX <- x <- df_exprs$mean_exprs_GTEX
rowData(sce_filtered)$mean_exprs_GTEX[is.na(x)] <- mean(x, na.rm=TRUE)

ca1 <- run_clonealign(sce_filtered, 
                     cnv_mat_remapped,
                     initial_shrinks = c(0, 10, 20), #args$initial_shrink,
                     n_repeats = 3,
                     mc_samples = 1,
                     learning_rate = 0.1,
                     max_iter = 1e3,
                     data_init_mu = TRUE,
                     clone_call_probability = 0.9)

ca2 <- run_clonealign(sce_filtered, 
                     cnv_mat_remapped,
                     initial_shrinks = c(0, 10, 20), #args$initial_shrink,
                     n_repeats = 3,
                     mc_samples = 1,
                     learning_rate = 0.1,
                     max_iter = 1e3,
                     data_init_mu = rowData(sce_filtered)$mean_exprs_GTEX,
                     clone_call_probability = 0.9)
```


