###
## Libraries and samples for analysis SA1035 10x
######################################################
library:
  SCRNA10X_SA_CHIP0079_001:
    mouse_id: SA1035X6XB03216
    treatmentSt: UUU
    batch_info: CHIP0079
    library_id: SCRNA10X_SA_CHIP0079_001
  SCRNA10X_SA_CHIP0079_002:
    mouse_id: SA1035X6XB03211
    treatmentSt: UTT
    batch_info: CHIP0079
    library_id: SCRNA10X_SA_CHIP0079_002
  SCRNA10X_SA_CHIP0142_002:
    mouse_id: SA1035X4XB02879
    treatmentSt: U
    batch_info: CHIP0142
    library_id: SCRNA10X_SA_CHIP0142_002
  SCRNA10X_SA_CHIP0142_004:
    mouse_id: SA1035X6XB03209
    treatmentSt: UTU
    batch_info: CHIP0142
    library_id: SCRNA10X_SA_CHIP0142_004
  SCRNA10X_SA_CHIP0145_001:
    mouse_id: SA1035X7XB03338
    treatmentSt: UTTT
    batch_info: CHIP0145
    library_id: SCRNA10X_SA_CHIP0145_001
  SCRNA10X_SA_CHIP0145_002:
    mouse_id: SA1035X7XB03340
    treatmentSt: UTTU
    batch_info: CHIP0145
    library_id: SCRNA10X_SA_CHIP0145_002
  SCRNA10X_SA_CHIP0151_001:
    mouse_id: SA1035X8XB03425
    treatmentSt: UTTTT
    batch_info: CHIP0151
    library_id: SCRNA10X_SA_CHIP0151_001
  SCRNA10X_SA_CHIP0162_001:
    mouse_id: SA1035X8XB03420
    treatmentSt: UTTTU
    batch_info: CHIP0162
    library_id: SCRNA10X_SA_CHIP0162_001
  SCRNA10X_SA_CHIP0162_002:
    mouse_id: SA1035X7XB03502
    treatmentSt: UUUU
    batch_info: CHIP0162
    library_id: SCRNA10X_SA_CHIP0162_002
  SCRNA10X_SA_CHIP0175_002:
    mouse_id: SA1035X8XB03631
    treatmentSt: UUUUU
    batch_info: CHIP0175
    library_id: SCRNA10X_SA_CHIP0175_002
  SCRNA10X_SA_CHIP0071_000:
    mouse_id: SA1035X5XB03015
    treatmentSt: UT
    batch_info: CHIP_UBC
    library_id: SCRNA10X_SA_CHIP0071_000
  SCRNA10X_SA_CHIP0076_000:
    mouse_id: SA1035X5XB03021
    treatmentSt: UU
    batch_info: CHIP_UBC
    library_id: SCRNA10X_SA_CHIP0076_000



# Snakemake parameters
############################

# Snakemake activated rules
############################
download_data: False
merge_data: False
verification_qc: True
filter_data: True
merge_filter_data: True
normalize_data: False
clustering_data: False
deg_analysis: False
batch_effect_estimation: False

# Snakemake filtering data params
############################
max_mito: 25
max_ribo: 60
min_pc_detected: 500
min_features: 1000
min_pc_sum: 1000


# Directory parameters: Please update all fields
# nextflow_dir: for corrupt-grow pipeline only
############################################
project_dir: '/home/htran/Projects/farhia_project/rscript/'
download_dir: '/home/htran/storage/datasets/drug_resistance_RNAseq'
results_dir: '/home/htran/storage/datasets/drug_resistance'
